### ISSUE TITLE
[Request] Assignable hotkeys for options and submenus?

### ISSUE THREAD

**Issue by GanerCodes** [phillbush/pmenu#12]
If there was a way to bind keys for going to a specific command that would be really helpful, ex. whenever I add something to my utilities menu the number of times I need to press tab changes, plus it would just make navigation faster in general

**Comment by phillbush** [comment]
There are already other applications that bind keypresses to commands. They are specialized in doing that, and do that job very well.  
More advanced keyboard control to run a given menu entry should be done by other applications such as sxhkd.  
I, for example, have a menu entry for spawning a Xterm window in pmenu, and also an entry in my sxhkdrc to spawn a terminal when pressing Alt+T.

**Comment by GanerCodes** [comment]
I'm more referring to ones that only work in the pmenu, like you could bind numbers 1-5 to each slice in some menu

**Comment by phillbush** [comment]
πmenu was meant to be used with a mouse, it has this pie-shape to [benefit from Fitts' law](https://news.ycombinator.com/item?id=16614889).   
Keyboard input more complex than (counter)clockwise navigation will not be implemented, because it would depend on the number of (and relative position of) the slices on the menu.

**Comment by GanerCodes** [comment]
I'm not referring to having it automatically generated just some way to assign a key to a specific slice like you would an image

**Comment by phillbush** [comment]
This would require code to parse the input to get the keybinding to assign to a slice.  
In order to keep the code simple and maintainable, and since the main premise of pmenu is to be usable primarily with the mouse, I will not implement that, sorry.  
If you want to fork pmenu and add this feature yourself, feel free to do that.

**Comment by GanerCodes** [comment]
btw I made a fork, It's done really jankily but it seemed pretty simple
