### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by nrts0** [phillbush/pmenu#18]
Hello, the build process fails because a file, defs.h, cannot be found.
I see it is not in the project directory, where can I find it?
Thanks.

**Comment by phillbush** [comment]
Oh, sorry about that.
I was testing a few changes and forgot to add that file.
(I should have been testing those changes on a separate branch rather than master, :)

Thanks for reporting it. It should compile now with the new features (support for old X11 fonts alongside Xft fonts, and support for motif/3D shadow) working.

**Comment by nrts0** [comment]
Nice, thanks!
