### ISSUE TITLE
Eliminate Compilation Warnings

### ISSUE THREAD

**Issue by CorporalCrawdad** [phillbush/pmenu#3]
There are apparently a few unused variables and an implicitly defined nanosleep().
Its an easy fix of including <time.h>, removing unsigned x, y from initpie(), and removing struct Slice *prevslice from main()

I don't know if these are intended for future use, but after some cursory pmenu usage it doesn't seem to break anything. I can make a PR with the changes, but its 5 line deletions and one include addition.

*accidentally posted to https://github.com/phillbush/xmenu/issues/13

**Comment by phillbush** [comment]
Sorry for those unused variables, they were used before but I forgot to remove them.

The variables in initpie() were used in a previous version, but I removed their code and forgot to remove the variables.

The prevslice (which is in run(), not in main()) were for a experiment I did on the develop branch, but for some reason I merged the variables into the master branch...

Strangely, I do not get compilation warnings with <time.h> in my system so that's why I have not noticed this problem.
